# Generated by Django 4.1 on 2022-11-06 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=30, unique=True)),
                ('seating_capacity', models.IntegerField()),
                ('service_type', models.CharField(max_length=100)),
                ('bus_model', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Bus',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('cnic', models.CharField(max_length=13, unique=True)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('address', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Driver',
            },
        ),
        migrations.CreateModel(
            name='Fares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Fares',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.BooleanField()),
                ('phone', models.CharField(max_length=13)),
                ('cnic', models.CharField(max_length=13)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Passenger',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Route',
            },
        ),
        migrations.CreateModel(
            name='RouteAssignedToBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.route')),
            ],
            options={
                'verbose_name_plural': 'RouteAssignedToBus',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('route_assg_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.routeassignedtobus')),
            ],
            options={
                'verbose_name_plural': 'Schedule',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Terminal',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher', models.CharField(max_length=200, unique=True)),
                ('refreshment', models.IntegerField()),
                ('washing', models.IntegerField()),
                ('parking', models.IntegerField()),
                ('toll', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('issuedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.schedule')),
                ('terminal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.terminal')),
            ],
            options={
                'verbose_name_plural': 'Voucher',
            },
        ),
        migrations.CreateModel(
            name='UserofTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.terminal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserofTerminal',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('cnic', models.CharField(max_length=13, unique=True)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('address', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserData',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher', models.CharField(default=None, max_length=100, null=True)),
                ('seat_no', models.IntegerField()),
                ('gender', models.BooleanField()),
                ('status', models.IntegerField()),
                ('type', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('bookedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.passenger')),
                ('fare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.fares')),
                ('issuedby', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.schedule')),
            ],
            options={
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_terminal', to='home.terminal'),
        ),
        migrations.AddField(
            model_name='route',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_terminal', to='home.terminal'),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField()),
                ('amount', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.passenger')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.schedule')),
            ],
            options={
                'verbose_name_plural': 'Refund',
            },
        ),
        migrations.CreateModel(
            name='Midpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.route')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.terminal')),
            ],
            options={
                'verbose_name_plural': 'Midpoint',
            },
        ),
        migrations.AddField(
            model_name='fares',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fare_destination_terminal', to='home.terminal'),
        ),
        migrations.AddField(
            model_name='fares',
            name='route_asg_to_bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.routeassignedtobus'),
        ),
        migrations.AddField(
            model_name='fares',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fare_source_terminal', to='home.terminal'),
        ),
        migrations.CreateModel(
            name='AssignedBusesToDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bus')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.driver')),
            ],
            options={
                'verbose_name_plural': 'AssignedBusesToDriver',
            },
        ),
    ]
