# Generated by Django 4.1 on 2022-11-07 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='destination',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_destination_terminal', to='home.terminal'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='source',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_source_terminal', to='home.terminal'),
        ),
    ]
