# Generated by Django 4.1 on 2022-11-14 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tickets_destination_tickets_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closedby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.schedule')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.terminal')),
            ],
            options={
                'verbose_name_plural': 'Closedby',
            },
        ),
    ]
