# Generated by Django 4.1 on 2022-11-26 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_closedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketsAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher', models.CharField(default=None, max_length=100, null=True)),
                ('fare', models.IntegerField()),
                ('seat_no', models.IntegerField()),
                ('gender', models.BooleanField()),
                ('status', models.IntegerField()),
                ('type', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('bookedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.passenger')),
                ('destination', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_destination_audit', to='home.terminal')),
                ('issuedby', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.schedule')),
                ('source', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_source_audit', to='home.terminal')),
            ],
            options={
                'verbose_name_plural': 'TicketsAudit',
            },
        ),
    ]
