# Generated by Django 4.1 on 2022-12-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_ticketsaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketsaudit',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
