# Generated by Django 4.1 on 2022-12-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_tickets_discount_ticketsaudit_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='mid_dept',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
