# Generated by Django 4.1 on 2022-12-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_terminal_tcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='tcode',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
