# Generated by Django 4.1 on 2022-12-11 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_terminal_tcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fares',
            name='route_asg_to_bus',
        ),
        migrations.AddField(
            model_name='fares',
            name='route',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.route'),
        ),
    ]
