# Generated by Django 4.1 on 2022-12-11 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_fares_route_asg_to_bus_fares_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fares',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.route'),
        ),
    ]
