# Generated by Django 4.1.4 on 2022-12-11 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_fares_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fares',
            name='route',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.route'),
        ),
    ]
